apiVersion: v2
name: clickhouse-operator
description: A Helm chart for clickhouse-operator
type: application
version: 0.18.3
appVersion: 0.18.3
dependencies:
- name: clickhouse-operator-crds
  version: "0.18.3"
  repository: "file://../crds"
