# Setup ClusterRoleBinding between ClusterRole and ServiceAccount.
# ClusterRoleBinding is namespace-less and must have unique name
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.clusterScoped }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: clickhouse-operator
{{- if not .Values.clusterScoped }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    {{- include "clickhouse-operator.labels" . | nindent 4 }}
    clickhouse.altinity.com/chop: 0.18.3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clickhouse-operator
subjects:
  - kind: ServiceAccount
    name: clickhouse-operator
    namespace: {{ .Release.Namespace }}
